/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DistributorWarehouseRole;

import UserInterface.ClinicRole.*;

/**
 *
 * @author relaince
 */
public class ManageVaccineInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccineInventoryJPanel
     */
    public ManageVaccineInventoryJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DISTRIBUTOR WAREHOUSE ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel2.setText("Number of Vaccines Available:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 76, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 70, 89, -1));

        jLabel3.setText("Number of Vaccines used:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 122, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 116, 89, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
