/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.HospitalRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.HospitalOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author relaince
 */
public class HospitalWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private HospitalOrganization hospitalOrg;
    private UserAccount ua;
    private HospitalEnterprise hospitalEnterprise;
    public HospitalWorkAreaJPanel(JPanel upc, HospitalEnterprise hospitalEnterprise, UserAccount ua, HospitalOrganization hospitalOrg, EcoSystem ecoSystem) {
        initComponents();
        userProcessContainer = upc;
        this.ecoSystem = ecoSystem;
        this.hospitalOrg = hospitalOrg;
        this.ua = ua;
        this.hospitalEnterprise = hospitalEnterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageClinicsjButton = new javax.swing.JButton();
        manageClinicAdminjButton = new javax.swing.JButton();
        sendEnrollmentRequestjButton = new javax.swing.JButton();
        manageOrderRequestjButton = new javax.swing.JButton();
        manageShipmentOrderjButton = new javax.swing.JButton();
        invoicejButton = new javax.swing.JButton();
        recallRequestjButton = new javax.swing.JButton();
        PHDVaccineShortageReportjButton = new javax.swing.JButton();
        reportVaccineReactionjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("HOSPITAL WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        manageClinicsjButton.setText("Manage Clinics");
        manageClinicsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageClinicsjButtonActionPerformed(evt);
            }
        });
        add(manageClinicsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 109, 218, -1));

        manageClinicAdminjButton.setText("Manage Clinic Admin ");
        manageClinicAdminjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageClinicAdminjButtonActionPerformed(evt);
            }
        });
        add(manageClinicAdminjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 156, 218, -1));

        sendEnrollmentRequestjButton.setText("Send Enrollment Request");
        sendEnrollmentRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEnrollmentRequestjButtonActionPerformed(evt);
            }
        });
        add(sendEnrollmentRequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 218, -1));

        manageOrderRequestjButton.setText("Manage Order Request");
        manageOrderRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderRequestjButtonActionPerformed(evt);
            }
        });
        add(manageOrderRequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 220, -1));

        manageShipmentOrderjButton.setText("Manage Shipment Order Request");
        manageShipmentOrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageShipmentOrderjButtonActionPerformed(evt);
            }
        });
        add(manageShipmentOrderjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 240, -1));

        invoicejButton.setText("Invoice");
        invoicejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicejButtonActionPerformed(evt);
            }
        });
        add(invoicejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 220, -1));

        recallRequestjButton.setText("Recall Request");
        recallRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallRequestjButtonActionPerformed(evt);
            }
        });
        add(recallRequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 220, -1));

        PHDVaccineShortageReportjButton.setText("Vaccine Shortage Report");
        PHDVaccineShortageReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHDVaccineShortageReportjButtonActionPerformed(evt);
            }
        });
        add(PHDVaccineShortageReportjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 220, -1));

        reportVaccineReactionjButton.setText("Report Vaccine Adverse Event");
        reportVaccineReactionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportVaccineReactionjButtonActionPerformed(evt);
            }
        });
        add(reportVaccineReactionjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageClinicsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageClinicsjButtonActionPerformed
        ManageClinicsJPanel mcjp = new ManageClinicsJPanel(userProcessContainer, hospitalEnterprise, ecoSystem);
        userProcessContainer.add("ManageClinicsJPanel",mcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageClinicsjButtonActionPerformed

    private void manageClinicAdminjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageClinicAdminjButtonActionPerformed
        ManageClinicAdminJPanel mcajp = new ManageClinicAdminJPanel(userProcessContainer, hospitalEnterprise, ecoSystem);
        userProcessContainer.add("ManageClinicAdminJPanel",mcajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageClinicAdminjButtonActionPerformed

    private void sendEnrollmentRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEnrollmentRequestjButtonActionPerformed
        EnrollmentRequestWorkAreaJPanel erwajp = new EnrollmentRequestWorkAreaJPanel(userProcessContainer, ua, hospitalEnterprise, ecoSystem);
        userProcessContainer.add("EnrollmentRequestWorkAreaJPanel",erwajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sendEnrollmentRequestjButtonActionPerformed

    private void manageOrderRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderRequestjButtonActionPerformed
        ManageHospitalOrderRequestJPanel mhorjp = new ManageHospitalOrderRequestJPanel(userProcessContainer, hospitalEnterprise, ua, hospitalOrg, ecoSystem);
        userProcessContainer.add("ManageHospitalOrderRequestJPanel",mhorjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrderRequestjButtonActionPerformed

    private void manageShipmentOrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageShipmentOrderjButtonActionPerformed
        HospitalManageShipmentOrderJPanel hmsojp = new HospitalManageShipmentOrderJPanel(userProcessContainer, hospitalEnterprise, ua, hospitalOrg, ecoSystem);
        userProcessContainer.add("HospitalManageShipmentOrderJPanel",hmsojp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
                
    }//GEN-LAST:event_manageShipmentOrderjButtonActionPerformed

    private void invoicejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicejButtonActionPerformed
        HospitalInvoiceJPanel hijp = new HospitalInvoiceJPanel(userProcessContainer, hospitalEnterprise, ua, hospitalOrg, ecoSystem);
        userProcessContainer.add("HospitalInvoiceJPanel",hijp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_invoicejButtonActionPerformed

    private void recallRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallRequestjButtonActionPerformed
        HospitalRecallRequestJPanel hrrjp = new HospitalRecallRequestJPanel(userProcessContainer, hospitalEnterprise, ua, hospitalOrg, ecoSystem);
        userProcessContainer.add("HospitalRecallRequestJPanel",hrrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_recallRequestjButtonActionPerformed

    private void PHDVaccineShortageReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHDVaccineShortageReportjButtonActionPerformed
        HospitalVaccineShortageJPanel hvsjp = new HospitalVaccineShortageJPanel(userProcessContainer, ua, hospitalEnterprise, hospitalOrg, ecoSystem);
        userProcessContainer.add("HospitalVaccineShortageJPanel",hvsjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_PHDVaccineShortageReportjButtonActionPerformed

    private void reportVaccineReactionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportVaccineReactionjButtonActionPerformed
        HospitalReportVaccineAdverseEventJPanel hrvaejp = new HospitalReportVaccineAdverseEventJPanel(userProcessContainer, ua, hospitalEnterprise, hospitalOrg, ecoSystem);
        userProcessContainer.add("HospitalReportVaccineAdverseEventJPanel",hrvaejp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportVaccineReactionjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PHDVaccineShortageReportjButton;
    private javax.swing.JButton invoicejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageClinicAdminjButton;
    private javax.swing.JButton manageClinicsjButton;
    private javax.swing.JButton manageOrderRequestjButton;
    private javax.swing.JButton manageShipmentOrderjButton;
    private javax.swing.JButton recallRequestjButton;
    private javax.swing.JButton reportVaccineReactionjButton;
    private javax.swing.JButton sendEnrollmentRequestjButton;
    // End of variables declaration//GEN-END:variables
}
