/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CDCRole;

import Business.EcoSystem;
import Business.Enterprise.CDCEnterprise;
import Business.Organization.CDCOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author relaince
 */
public class CDCOrgWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private CDCEnterprise cdcEnterprise;
    private UserAccount account;
    private CDCOrganization cdcOrganization;
    public CDCOrgWorkAreaJPanel(JPanel upc,CDCEnterprise cdcEnterprise,UserAccount account,CDCOrganization cdcOrganization,EcoSystem ecoSystem) {
        initComponents();
        userProcessContainer = upc;
        this.ecoSystem = ecoSystem;
        this.cdcEnterprise = cdcEnterprise;
        this.account = account;
        this.cdcOrganization = cdcOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePHDjButton = new javax.swing.JButton();
        managePHDAdminjButton = new javax.swing.JButton();
        manageVaccineAllotmentjButton = new javax.swing.JButton();
        vaccineDistributionjButton = new javax.swing.JButton();
        postVaccineShortagejButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageInvoicejButton = new javax.swing.JButton();
        VaccineReactionReportjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managePHDjButton.setText("Manage PHD ");
        managePHDjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePHDjButtonActionPerformed(evt);
            }
        });
        add(managePHDjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        managePHDAdminjButton.setText("Manage PHD Admin");
        managePHDAdminjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePHDAdminjButtonActionPerformed(evt);
            }
        });
        add(managePHDAdminjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        manageVaccineAllotmentjButton.setText("Manage Vaccine Allotment");
        manageVaccineAllotmentjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVaccineAllotmentjButtonActionPerformed(evt);
            }
        });
        add(manageVaccineAllotmentjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        vaccineDistributionjButton.setText("Vaccine Distribution Overview");
        vaccineDistributionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineDistributionjButtonActionPerformed(evt);
            }
        });
        add(vaccineDistributionjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        postVaccineShortagejButton.setText("Post Vaccine Shortage");
        postVaccineShortagejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postVaccineShortagejButtonActionPerformed(evt);
            }
        });
        add(postVaccineShortagejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel1.setText("CDC WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        manageInvoicejButton.setText("Manage Invoice");
        manageInvoicejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInvoicejButtonActionPerformed(evt);
            }
        });
        add(manageInvoicejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        VaccineReactionReportjButton.setText("View Vaccine Reactions Report");
        VaccineReactionReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaccineReactionReportjButtonActionPerformed(evt);
            }
        });
        add(VaccineReactionReportjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void managePHDjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePHDjButtonActionPerformed
        ManagePHDJPanel mphdjp = new ManagePHDJPanel(userProcessContainer, cdcEnterprise, ecoSystem);
        userProcessContainer.add("ManagePHDJPanel", mphdjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePHDjButtonActionPerformed

    private void managePHDAdminjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePHDAdminjButtonActionPerformed
        ManagePHDAdminJPanel mphdajp = new ManagePHDAdminJPanel(userProcessContainer, cdcEnterprise, ecoSystem);
        userProcessContainer.add("ManagePHDAdminJPanel", mphdajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePHDAdminjButtonActionPerformed

    private void manageVaccineAllotmentjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVaccineAllotmentjButtonActionPerformed
        ManageVaccineAllotmentJPanel mvajp = new ManageVaccineAllotmentJPanel(userProcessContainer, account, cdcEnterprise, cdcOrganization, ecoSystem);
        userProcessContainer.add("ManageVaccineAllotmentJPanel", mvajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageVaccineAllotmentjButtonActionPerformed

    private void vaccineDistributionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineDistributionjButtonActionPerformed
        VaccineDistributionOverviewJPanel vdojp = new VaccineDistributionOverviewJPanel(userProcessContainer, account, cdcEnterprise, cdcOrganization, ecoSystem);
        userProcessContainer.add("VaccineDistributionOverviewJPanel", vdojp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_vaccineDistributionjButtonActionPerformed

    private void postVaccineShortagejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postVaccineShortagejButtonActionPerformed
        CDCReportVaccineShortageJPanel cdcrvsjp = new CDCReportVaccineShortageJPanel(userProcessContainer, account, cdcEnterprise, cdcOrganization, ecoSystem);
        userProcessContainer.add("CDCReportVaccineShortageJPanel", cdcrvsjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_postVaccineShortagejButtonActionPerformed

    private void manageInvoicejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInvoicejButtonActionPerformed
        CDCInvoiceJPanel cdcijp = new CDCInvoiceJPanel(userProcessContainer, account, cdcEnterprise, cdcOrganization, ecoSystem);
        userProcessContainer.add("CDCInvoiceJPanel", cdcijp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageInvoicejButtonActionPerformed

    private void VaccineReactionReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaccineReactionReportjButtonActionPerformed
        ViewVaccineReactionReportJPanel vvrrjp = new ViewVaccineReactionReportJPanel(userProcessContainer, cdcEnterprise, account, cdcOrganization, ecoSystem);
        userProcessContainer.add("ViewVaccineReactionReportJPanel", vvrrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_VaccineReactionReportjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VaccineReactionReportjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageInvoicejButton;
    private javax.swing.JButton managePHDAdminjButton;
    private javax.swing.JButton managePHDjButton;
    private javax.swing.JButton manageVaccineAllotmentjButton;
    private javax.swing.JButton postVaccineShortagejButton;
    private javax.swing.JButton vaccineDistributionjButton;
    // End of variables declaration//GEN-END:variables
}
