/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DistributorRole;

import Business.EcoSystem;
import Business.Enterprise.DistributorEnterprise;
import Business.Organization.DistributorOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author relaince
 */
public class DistributorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount ua;
    private DistributorEnterprise distEnterprise;
    private DistributorOrganization distOrganization;
    private EcoSystem ecoSystem;
    
    public DistributorWorkAreaJPanel(JPanel upc, DistributorEnterprise distEnterprise, UserAccount ua, DistributorOrganization distOrganization, EcoSystem ecoSystem) {
        initComponents();
        userProcessContainer = upc;
        this.ecoSystem = ecoSystem;
        this.distEnterprise = distEnterprise;
        this.ua = ua;
        this.distOrganization = distOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageWarehousejButton = new javax.swing.JButton();
        manageWarehouseAdminjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel1.setText("DISTRIBUTOR WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 20));

        manageWarehousejButton.setText("Manage Warehouse");
        manageWarehousejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWarehousejButtonActionPerformed(evt);
            }
        });
        add(manageWarehousejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        manageWarehouseAdminjButton.setText("Manage Warehouse Admin");
        manageWarehouseAdminjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWarehouseAdminjButtonActionPerformed(evt);
            }
        });
        add(manageWarehouseAdminjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageWarehousejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWarehousejButtonActionPerformed
        ManageDistributorWarehouseJPanel mdwjp = new ManageDistributorWarehouseJPanel(userProcessContainer, distEnterprise, ecoSystem);
        userProcessContainer.add("ManageDistributorWarehouseJPanel",mdwjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageWarehousejButtonActionPerformed

    private void manageWarehouseAdminjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWarehouseAdminjButtonActionPerformed
        ManageDistributorWarehouseAdminJPanel mdwajp = new ManageDistributorWarehouseAdminJPanel(userProcessContainer, distEnterprise, ecoSystem);
        userProcessContainer.add("ManageDistributorWarehouseAdminJPanel",mdwajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageWarehouseAdminjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageWarehouseAdminjButton;
    private javax.swing.JButton manageWarehousejButton;
    // End of variables declaration//GEN-END:variables
}
