/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Network.Network;
import Business.Organization.PatientOrganization;
import Business.Person.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author insignia
 */
public class PatientInsuranceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private ClinicEnterprise clinicEnt;
    private PatientOrganization patientOrganization;
    private UserAccount account;
    public PatientInsuranceJPanel(JPanel upc, ClinicEnterprise clinicEnt, UserAccount account, PatientOrganization patientOrganization, EcoSystem ecoSystem) {
        initComponents();
        userProcessContainer = upc;
        this.ecoSystem = ecoSystem;
        this.clinicEnt = clinicEnt;
        this.patientOrganization = patientOrganization;
        this.account = account;
        
        insuranceStatusjComboBox.removeAllItems();
        insuranceStatusjComboBox.addItem("Uninsured");
        insuranceStatusjComboBox.addItem("Under Insured");
        insuranceStatusjComboBox.addItem("Private Insurance");
        
        insuranceCompanyjComboBox.removeAllItems();
        for(Network network : ecoSystem.getNetworkList()){
            for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList())
                if(e instanceof InsuranceEnterprise){
                    insuranceCompanyjComboBox.addItem(e);
                }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insuranceStatusjComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submitjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        OrderVaccinesjButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        insuranceCompanyjComboBox = new javax.swing.JComboBox();

        insuranceStatusjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        insuranceStatusjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceStatusjComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Patient Insurance JPanel");

        jLabel2.setText("Insurance Status:");

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        backjButton.setText("<< Back");

        OrderVaccinesjButton.setText("Order Vaccines");
        OrderVaccinesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderVaccinesjButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Insurance Company:");

        insuranceCompanyjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        insuranceCompanyjComboBox.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(backjButton)
                        .addGap(18, 18, 18)
                        .addComponent(submitjButton)
                        .addGap(18, 18, 18)
                        .addComponent(OrderVaccinesjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insuranceStatusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insuranceCompanyjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceStatusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(insuranceCompanyjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(submitjButton)
                    .addComponent(OrderVaccinesjButton))
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        String insuranceStatus = (String)insuranceStatusjComboBox.getSelectedItem();
        Patient patient = (Patient)account.getPerson();
        patient.setInsuranceStatus(insuranceStatus);
        String insuranceCompany = (String)insuranceCompanyjComboBox.getSelectedItem();
        patient.setInsuranceCompany(insuranceCompany);
//        for(Person person : patientOrganization.getPersonDirectory().getPersonList()){
//            if(person instanceof Patient){
//                patient = (Patient)person;
//            }
//        }
        
    }//GEN-LAST:event_submitjButtonActionPerformed

    private void OrderVaccinesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderVaccinesjButtonActionPerformed
        PatientOrderRequestWorkAreaJPanel porwajp = new PatientOrderRequestWorkAreaJPanel(userProcessContainer, account, clinicEnt, patientOrganization, ecoSystem);
        userProcessContainer.add("PatientOrderRequestWorkAreaJPanel",porwajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_OrderVaccinesjButtonActionPerformed

    private void insuranceStatusjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceStatusjComboBoxActionPerformed
        if(insuranceStatusjComboBox.getSelectedItem() == "Private Insurance")
        {
            insuranceCompanyjComboBox.setEnabled(true);
        }
    }//GEN-LAST:event_insuranceStatusjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OrderVaccinesjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox insuranceCompanyjComboBox;
    private javax.swing.JComboBox insuranceStatusjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton submitjButton;
    // End of variables declaration//GEN-END:variables
}
