/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ClinicOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Person.Vaccine;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author insignia
 */
public class PatientRequestOrderJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private ClinicEnterprise clinicEnt;
    private PatientOrganization patientOrganization;
    private EcoSystem ecoSystem;
    private Vaccine vaccine;
    //private static int count;
    public PatientRequestOrderJPanel(JPanel upc,UserAccount account, Vaccine vaccine, ClinicEnterprise clinicEnt, PatientOrganization patientOrganization,EcoSystem ecoSystem) {
        initComponents();
        userProcessContainer = upc;
        this.account = account;
        this.clinicEnt = clinicEnt;
        this.patientOrganization = patientOrganization;
        this.ecoSystem = ecoSystem;
        this.vaccine = vaccine;
        //count++;
        
        vaccineNameTextField.setText(vaccine.getVaccineName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vaccineNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantityjTextField = new javax.swing.JTextField();
        submitjButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        requestIDjTextField = new javax.swing.JTextField();

        jLabel1.setText("Request Order JPanel");

        jLabel2.setText("Vaccine Name:");

        jLabel3.setText("Quantity:");

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Request ID:");

        requestIDjTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vaccineNameTextField)
                            .addComponent(quantityjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(requestIDjTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitjButton)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(requestIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vaccineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(submitjButton)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        
//        String vaccineName;
//        try
//        {
//        vaccineName = vaccineNameTextField.getText();
//         if ((vaccineNameTextField.getText().startsWith(" ")) || (vaccineNameTextField.getText().isEmpty()))
//            throw new Exception(" Please enter valid characters for message ");
//        }       
//        catch (Exception e) {
//        JOptionPane.showMessageDialog(null,e.getMessage());
//        return;
//        }
        
        int quantity;
        quantity = Integer.parseInt(quantityjTextField.getText());
         
        OrderRequest orderRequest = new OrderRequest();
        
        orderRequest.setVaccineName(vaccine.getVaccineName());
        orderRequest.setQuantity(quantity);
        orderRequest.setSender(account);
        orderRequest.setStatus("sent");
        orderRequest.setRequestID(orderRequest.getRequestID());
        orderRequest.setLocation(clinicEnt.getLocation());
        orderRequest.setEnterpriseType(clinicEnt.getEnterpriseType().getValue());
        orderRequest.setEnterpriseName(clinicEnt.getName());
            System.out.println("clinicEnterprise.getName(): " +clinicEnt.getName());
        
        
        requestIDjTextField.setText(String.valueOf(orderRequest.getRequestID()));
        
        Organization org = null;
        ClinicEnterprise clinicE = null;
        for(Network n : ecoSystem.getNetworkList()){
            boolean flag = false;
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                if(clinicEnt.getLocation().equals(e.getLocation())){
                    System.out.println("enterprise: " +e.getLocation());
                    if(e instanceof ClinicEnterprise){
                    //if(e.getEnterpriseType().getValue().equals("Hospital")){
                        clinicE = (ClinicEnterprise)e;
                            if(clinicE.getName().equals(clinicEnt.getName())){
                                for(Organization o : clinicE.getOrganizationDirectory().getOrganizationList()){
                                if(o instanceof ClinicOrganization){
                                   //System.out.println("instance of provider org");
                                 org = o;
                                 flag = true;
                                 break;
                                    
                            }
                        }
                    }
                }
            }
                 if(flag==true)
                {
                    break;
                }
            }
                                
        
        if(org!=null){
            org.getWorkQueue().getWorkRequestList().add(orderRequest);
            account.getWorkQueue().getWorkRequestList().add(orderRequest);
            System.out.println("work request added");
        }
        if(org==null){
            System.out.println("org is null");
        }
        JOptionPane.showMessageDialog(null, "Order request sent");
        vaccineNameTextField.setText("");
        quantityjTextField.setText("");
        return;
        
        }         
    }//GEN-LAST:event_submitjButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField quantityjTextField;
    private javax.swing.JTextField requestIDjTextField;
    private javax.swing.JButton submitjButton;
    private javax.swing.JTextField vaccineNameTextField;
    // End of variables declaration//GEN-END:variables
}
