/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.ClinicRole;

import Business.EcoSystem;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author relaince
 */
public class ClinicWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private ClinicOrganization clinicOrganization;
    private EcoSystem ecoSystem;
    public ClinicWorkAreaJPanel(JPanel upc,UserAccount account, Enterprise enterprise, ClinicOrganization clinicOrganization, EcoSystem ecoSystem) {
        initComponents();
        userProcessContainer = upc;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.clinicOrganization = clinicOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageVaccineInventoryjButton = new javax.swing.JButton();
        vaccineOrderRequestjButton = new javax.swing.JButton();
        manageShipmentStatusButton = new javax.swing.JButton();
        recallRequestjButton = new javax.swing.JButton();
        PHDVaccineShortageReportjButton = new javax.swing.JButton();
        managePatientOrderRequestjButton = new javax.swing.JButton();
        reportVaccineReactionjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel1.setText("CLINIC WORK AREA ");

        manageVaccineInventoryjButton.setText("Manage Vaccine Inventory");
        manageVaccineInventoryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVaccineInventoryjButtonActionPerformed(evt);
            }
        });

        vaccineOrderRequestjButton.setText("Vaccine Order Request >>");
        vaccineOrderRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineOrderRequestjButtonActionPerformed(evt);
            }
        });

        manageShipmentStatusButton.setText(" ManageShipment Status");
        manageShipmentStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageShipmentStatusButtonActionPerformed(evt);
            }
        });

        recallRequestjButton.setText("Recall Request");
        recallRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallRequestjButtonActionPerformed(evt);
            }
        });

        PHDVaccineShortageReportjButton.setText("Vaccine Shortage Report");
        PHDVaccineShortageReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHDVaccineShortageReportjButtonActionPerformed(evt);
            }
        });

        managePatientOrderRequestjButton.setText("Manage Patient Order Request");
        managePatientOrderRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientOrderRequestjButtonActionPerformed(evt);
            }
        });

        reportVaccineReactionjButton.setText("Report Vaccine Adverse Event");
        reportVaccineReactionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportVaccineReactionjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageShipmentStatusButton)
                    .addComponent(vaccineOrderRequestjButton)
                    .addComponent(recallRequestjButton)
                    .addComponent(PHDVaccineShortageReportjButton)
                    .addComponent(managePatientOrderRequestjButton)
                    .addComponent(reportVaccineReactionjButton)
                    .addComponent(jLabel1)
                    .addComponent(manageVaccineInventoryjButton))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageVaccineInventoryjButton)
                .addGap(18, 18, 18)
                .addComponent(vaccineOrderRequestjButton)
                .addGap(18, 18, 18)
                .addComponent(manageShipmentStatusButton)
                .addGap(18, 18, 18)
                .addComponent(recallRequestjButton)
                .addGap(18, 18, 18)
                .addComponent(PHDVaccineShortageReportjButton)
                .addGap(18, 18, 18)
                .addComponent(managePatientOrderRequestjButton)
                .addGap(18, 18, 18)
                .addComponent(reportVaccineReactionjButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageVaccineInventoryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVaccineInventoryjButtonActionPerformed
        ManageVaccineInventoryJPanel mvijp = new ManageVaccineInventoryJPanel(userProcessContainer,clinicOrganization);
        userProcessContainer.add("ManageVaccineInventoryJPanel",mvijp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageVaccineInventoryjButtonActionPerformed

    private void vaccineOrderRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineOrderRequestjButtonActionPerformed
        ClinicVaccineOrderRequestWorkAreaJPanel cvorwajp = new ClinicVaccineOrderRequestWorkAreaJPanel(userProcessContainer,account,enterprise, clinicOrganization, ecoSystem);
        userProcessContainer.add("ClinicVaccineOrderRequestWorkAreaJPanel",cvorwajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_vaccineOrderRequestjButtonActionPerformed

    private void manageShipmentStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageShipmentStatusButtonActionPerformed
        ShipmentStatusJPanel ssjp = new ShipmentStatusJPanel(userProcessContainer,account,enterprise, clinicOrganization, ecoSystem);
        userProcessContainer.add("ShipmentStatusJPanel",ssjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageShipmentStatusButtonActionPerformed

    private void recallRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallRequestjButtonActionPerformed
        ClinicRecallRequestJPanel crrjp = new ClinicRecallRequestJPanel(userProcessContainer, (ClinicEnterprise)enterprise, account, clinicOrganization, ecoSystem);
        userProcessContainer.add("ClinicRecallRequestJPanel",crrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_recallRequestjButtonActionPerformed

    private void PHDVaccineShortageReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHDVaccineShortageReportjButtonActionPerformed
        ClinicVaccineShortageJPanel cvsjp = new ClinicVaccineShortageJPanel(userProcessContainer, account, (ClinicEnterprise)enterprise, clinicOrganization, ecoSystem);
        userProcessContainer.add("ClinicVaccineShortageJPanel",cvsjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_PHDVaccineShortageReportjButtonActionPerformed

    private void managePatientOrderRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientOrderRequestjButtonActionPerformed
        ClinicOrderRequestWorkAreaJPanel corwajp = new ClinicOrderRequestWorkAreaJPanel(userProcessContainer, account, (ClinicEnterprise)enterprise, clinicOrganization, ecoSystem);
        userProcessContainer.add("ClinicOrderRequestWorkAreaJPanel",corwajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePatientOrderRequestjButtonActionPerformed

    private void reportVaccineReactionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportVaccineReactionjButtonActionPerformed
          ClinicReportVaccineAdverseEventJPanel crvaejp = new ClinicReportVaccineAdverseEventJPanel(userProcessContainer, account, (ClinicEnterprise)enterprise, clinicOrganization, ecoSystem);
          userProcessContainer.add("ClinicReportVaccineAdverseEventJPanel",crvaejp);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_reportVaccineReactionjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PHDVaccineShortageReportjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton managePatientOrderRequestjButton;
    private javax.swing.JButton manageShipmentStatusButton;
    private javax.swing.JButton manageVaccineInventoryjButton;
    private javax.swing.JButton recallRequestjButton;
    private javax.swing.JButton reportVaccineReactionjButton;
    private javax.swing.JButton vaccineOrderRequestjButton;
    // End of variables declaration//GEN-END:variables
}
