/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClinicRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ClinicOrganization;
import Business.Person.Clinician;
import Business.Person.Person;
import Business.Person.Vaccine;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ShippingRequest;
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author insignia
 */
public class ClinicProcessShipmentJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private ClinicOrganization clinicOrganization;
    private EcoSystem ecoSystem;
    private ShippingRequest request;
    private Calendar calendar;
    private Date d;
    public ClinicProcessShipmentJPanel(JPanel upc,UserAccount account, ShippingRequest request, Enterprise enterprise, ClinicOrganization clinicOrganization, EcoSystem ecoSystem) {
        initComponents();
        userProcessContainer = upc;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.clinicOrganization = clinicOrganization;
        this.request = request;
        calendar = Calendar.getInstance();
        d = calendar.getTime();
        
        statusjComboBox.removeAllItems();
        statusjComboBox.addItem("Received");
        statusjComboBox.addItem("Not Received Yet");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statusjComboBox = new javax.swing.JComboBox();
        submitjButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel1.setText("CLINIC PROCESS SHIPMENT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Status:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        statusjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(statusjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 55, -1, -1));

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });
        add(submitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        backButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        if(!request.getOrderResult().equals("Received")){
        String status = (String)statusjComboBox.getSelectedItem();
        if(status.equals("Received")){
            request.setStatus("Completed");
            request.setOrderResult("Received");
            Clinician clinician = null;
            for(Person p : clinicOrganization.getPersonDirectory().getPersonList()){
            if(p instanceof Clinician){
                clinician = (Clinician)p;
                Vaccine vaccine = clinician.getVaccineCatalog().addVaccine();
                vaccine.setVaccineName(request.getVaccineName());
                vaccine.setQuantity(request.getQuantity());
                vaccine.setDateManufactured(request.getManufactureDate());
                vaccine.setManufacturer(request.getManufacturer());
                vaccine.setPrice(request.getPrice());
                vaccine.setLotNumber(request.getLotNumber());
                vaccine.setExpiryDate(request.getExpiryDate());
                }
            }
        }
        if(status.equals("Not Received Yet"))
            {
                request.setStatus("Pending");
                request.setOrderResult("Pending");
            }
         
        JOptionPane.showMessageDialog(null, "Result submitted");
            
          
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        
//                Date date = shippingDatejDateChooser.getDate();
//                String strDate = DateFormat.getDateInstance().format(date);
//                 System.out.println("calendar: " +d);
//                 System.out.println("date: " +date);
//                 if(date.after(d)){
//                     request.setProcessDate(strDate);
//                     request.setOrderResult("Received");
//                     
//                     }
//                 if(date.equals(d)){
//                     request.setProcessDate(strDate);
//                     request.setOrderResult("Received");
//                     
//                     }
//                 if(date.before(d))
//                 {
//                         JOptionPane.showMessageDialog(null, "Please select a valid date");
//                         return;
//                     }
//        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Result already submitted");
        }
    }//GEN-LAST:event_submitjButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox statusjComboBox;
    private javax.swing.JButton submitjButton;
    // End of variables declaration//GEN-END:variables
}
