/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PharmaceuticalRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalEnterprise;
import Business.Organization.PharmaceuticalOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author relaince
 */
public class PharmaceuticalWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private PharmaceuticalOrganization pharOrg;
    private UserAccount ua;
    private PharmaceuticalEnterprise phEnterprise;
    public PharmaceuticalWorkAreaJPanel(JPanel upc, PharmaceuticalEnterprise phEnterprise, UserAccount ua, PharmaceuticalOrganization pharOrg, EcoSystem ecoSystem) {
        initComponents();
        userProcessContainer = upc;
        this.ecoSystem = ecoSystem;
        this.pharOrg = pharOrg;
        this.ua = ua;
        this.phEnterprise = phEnterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageClinicsjButton = new javax.swing.JButton();
        manageClinicAdminjButton = new javax.swing.JButton();
        sendEnrollmentRequestjButton = new javax.swing.JButton();
        manageOrderRequestjButton = new javax.swing.JButton();
        manageShipmentOrderjButton = new javax.swing.JButton();
        invoicejButton = new javax.swing.JButton();
        phdVaccineShortageReportjButton = new javax.swing.JButton();
        recallRequestjButton1 = new javax.swing.JButton();
        reportVaccineReactionjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel1.setText("PHARAMCEUTICAL WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        manageClinicsjButton.setText("Manage Clinics");
        manageClinicsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageClinicsjButtonActionPerformed(evt);
            }
        });
        add(manageClinicsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 218, -1));

        manageClinicAdminjButton.setText("Manage Clinic Admin ");
        manageClinicAdminjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageClinicAdminjButtonActionPerformed(evt);
            }
        });
        add(manageClinicAdminjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 218, -1));

        sendEnrollmentRequestjButton.setText("Send Enrollment Request");
        sendEnrollmentRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEnrollmentRequestjButtonActionPerformed(evt);
            }
        });
        add(sendEnrollmentRequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 218, -1));

        manageOrderRequestjButton.setText("Manage Order Request");
        manageOrderRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderRequestjButtonActionPerformed(evt);
            }
        });
        add(manageOrderRequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 220, -1));

        manageShipmentOrderjButton.setText("Manage Shipment Order Request");
        manageShipmentOrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageShipmentOrderjButtonActionPerformed(evt);
            }
        });
        add(manageShipmentOrderjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 230, -1));

        invoicejButton.setText("Invoice");
        invoicejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicejButtonActionPerformed(evt);
            }
        });
        add(invoicejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 220, -1));

        phdVaccineShortageReportjButton.setText("Vaccine Shortage Report");
        phdVaccineShortageReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phdVaccineShortageReportjButtonActionPerformed(evt);
            }
        });
        add(phdVaccineShortageReportjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 220, -1));

        recallRequestjButton1.setText("Recall Request");
        recallRequestjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallRequestjButton1ActionPerformed(evt);
            }
        });
        add(recallRequestjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 220, -1));

        reportVaccineReactionjButton.setText("Report Vaccine Adverse Event");
        reportVaccineReactionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportVaccineReactionjButtonActionPerformed(evt);
            }
        });
        add(reportVaccineReactionjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageClinicsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageClinicsjButtonActionPerformed
        ManageClinicsJPanel mcjp = new ManageClinicsJPanel(userProcessContainer, phEnterprise, ecoSystem);
        userProcessContainer.add("ManageClinicsJPanel",mcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageClinicsjButtonActionPerformed

    private void manageClinicAdminjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageClinicAdminjButtonActionPerformed
        ManageClinicAdminJPanel mcajp = new ManageClinicAdminJPanel(userProcessContainer, phEnterprise, ecoSystem);
        userProcessContainer.add("ManageClinicAdminJPanel",mcajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageClinicAdminjButtonActionPerformed

    private void sendEnrollmentRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEnrollmentRequestjButtonActionPerformed
        EnrollmentRequestWorkAreaJPanel serjp = new EnrollmentRequestWorkAreaJPanel(userProcessContainer, ua, phEnterprise, ecoSystem);
        userProcessContainer.add("SendEnrollmentRequestJPanel",serjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sendEnrollmentRequestjButtonActionPerformed

    private void manageOrderRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderRequestjButtonActionPerformed
        ManagePharmaceuticalOrderRequestJPanel mporjp = new ManagePharmaceuticalOrderRequestJPanel(userProcessContainer, ua, phEnterprise, pharOrg, ecoSystem);
        userProcessContainer.add("ManagePharmaceuticalOrderRequestJPanel",mporjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrderRequestjButtonActionPerformed

    private void manageShipmentOrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageShipmentOrderjButtonActionPerformed
        PharmaceuticalManageShipmentOrderJPanel pmsojp = new PharmaceuticalManageShipmentOrderJPanel(userProcessContainer,  ua, phEnterprise, pharOrg, ecoSystem);
        userProcessContainer.add("PharmaceuticalManageShipmentOrderJPanel",pmsojp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageShipmentOrderjButtonActionPerformed

    private void invoicejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicejButtonActionPerformed
        PharmaceuticalInvoiceJPanel pijp = new PharmaceuticalInvoiceJPanel(userProcessContainer, phEnterprise, ua, pharOrg, ecoSystem);
        userProcessContainer.add("PharmaceuticalInvoiceJPanel",pijp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_invoicejButtonActionPerformed

    private void phdVaccineShortageReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phdVaccineShortageReportjButtonActionPerformed
        PharmaceuticalVaccineShortageJPanel pvsjp = new PharmaceuticalVaccineShortageJPanel(userProcessContainer, ua, phEnterprise, pharOrg, ecoSystem);
        userProcessContainer.add("PharmaceuticalVaccineShortageJPanel",pvsjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_phdVaccineShortageReportjButtonActionPerformed

    private void recallRequestjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallRequestjButton1ActionPerformed
        PharmaceuticalRecallRequestJPanel prrjp = new PharmaceuticalRecallRequestJPanel(userProcessContainer, ua, pharOrg, ecoSystem);
        userProcessContainer.add("PharmaceuticalRecallRequestJPanel",prrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_recallRequestjButton1ActionPerformed

    private void reportVaccineReactionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportVaccineReactionjButtonActionPerformed
        PharmaceuticalReportVaccineAdverseEventJPanel phrvaejp = new PharmaceuticalReportVaccineAdverseEventJPanel(userProcessContainer, ua, phEnterprise, pharOrg, ecoSystem);
        userProcessContainer.add("PharmaceuticalReportVaccineAdverseEventJPanel",phrvaejp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportVaccineReactionjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton invoicejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageClinicAdminjButton;
    private javax.swing.JButton manageClinicsjButton;
    private javax.swing.JButton manageOrderRequestjButton;
    private javax.swing.JButton manageShipmentOrderjButton;
    private javax.swing.JButton phdVaccineShortageReportjButton;
    private javax.swing.JButton recallRequestjButton1;
    private javax.swing.JButton reportVaccineReactionjButton;
    private javax.swing.JButton sendEnrollmentRequestjButton;
    // End of variables declaration//GEN-END:variables
}
